package com.solvd.onlineshop.enums;

import com.solvd.onlineshop.utils.ApacheWordCount;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public enum Currencies {
    ABKHAZIANAPSAR("ABK"), AFGHANISTANAFGHANI("AFN"), ALBANIANLEK("ALL"), ALDERNEYPOUND("NONE"), ALGERIANDINAR("DZD"),
    ANDORRANFRANC("ADF"), ANDORRANPESETA("ADP"), ANGOLANKWANZA("AOA"), ANGOLANOLDKWANZA("AON"), ARGENTINEPESO("ARS"), ARMENIANDRAM("AMD"),
    ARTSAKHDRAM("NONE"), ARUBANFLORIN("AWG"), AUSTRALIANDOLLAR("AUD"), AUSTRIANSCHILLING("ATS"), AZERBAIJANINEWMANAT("AZN"),
    AZERBAIJANOLDMANAT("AZM"), BAHAMIANDOLLAR("BSD"), BAHRAINIDINAR("BHD"), BANGLADESHITAKA("BDT"), BARBADOSDOLLAR("BBD"),
    BELARUSIANOLDRUBLE("BYR"), BELARUSIANRUBLE("BYN"), BELGIANFRANC("BEF"), BELIZEDOLLAR("BZD"), BERMUDIANDOLLAR("BMD"),
    BHUTANESENGULTRUM("BTN"), BITCOIN("BTC"), BOLIVIANBOLIVIANO("BOB"), BOSNIAANDHERZEGOVINACONVERTIBLEMARK("BAM"),
    BOTSWANAPULA("BWP"), BRAZILIANREAL("BRL"), BRITISHPOUND("GBP"), BRUNEIDOLLAR("BND"), BULGARIANLEV("BGN"), BULGARIANOLDLEV("BGL"),
    BURMESEKYAT("MMK"), BURUNDIANFRANC("BIF"), CAMBODIANRIEL("KHR"), CANADIANDOLLAR("CAD"), CAPEVERDEANESCUDO("CVE"), CAYMANISLANDSDOLLAR("KYD"),
    CENTRALAFRICANCFAFRANC("BEAC/XAF"), CENTRALPACIFICFRANC("CFP"), CFPFRANC("XPF"), CHILEANPESO("CLP"), CHILEANUNIDADDEFOMENTO("CLF"),
    CHINESEYUANRENMINBI("CNY"), COLOMBIANPESO("COP"), COMORIANFRANC("KMF"), CONGOLESEFRANC("CDF"),
    COOKISLANDSDOLLAR("CKD"), COSTRICANCOLON("CRC"), CROATIANKUNA("HRK"), CUBANCONVERTIBLEPESO("CUC"), CUBANPESO("CUP"), CYPRUSPOUND("CYP"),
    CZECHKORUNA("CZK"), DANISHKRONE("DKK"), DJIBOUTIANFRANC("DJF"), DOMINICANPESO("DOP"), DUTCHGUILDER("NLG"), EASTERNCARIBBEANDOLLAR("XCD"),
    ECUADORSUCRE("ECS"), EGYPTIANPOUND("EGP"), ELSALVADORCOLON("SVC"), ERITREANNAKFA("ERN"), ESTONIANKROON("ERN"), ETHEREUM("ETH"),
    ETHIOPIANBIRR("ETB"), EURO("EUR"), EUROPEANCURRENCYUNIT("ECU"), FALKLANDISLANDSPOUND("FKP"), FAROESEKRONA("FOK"), FIJIANDOLLAR("FJD"),
    FINNISHMARKKA("FIM"), FRENCHFRANC("FRF"), GAMBIANDALASI("GMD"), GEORGIANLARI("GEL"), GERMANMARK("DEM"), GHANAIANCEDI("GHC"),
    GHANAIANNEWCEDI("GHS"), GIBRALTARPOUND("GIP"), GREEKDRACHMA("GRD"), GUATEMALANQUETZAL("GTQ"), GUERNSEYPOUND("GGP"),
    GUINEANFRANC("GNF"), GUYANESEDOLLAR("GYD"), HAITIANGOURDE("HTG"), HONDURANLEMPIRA("HNL"), HONGKONGDOLLAR("HKD"), HUNGARIANFORINT("HUF"),
    ICELANDICKRONA("ISK"), INDIANRUPEE("INR"), INDONESIANRUPIAH("IDR"), IRANIANRIAL("IRR"), IRAQIDINAR("IQD"), IRISHPUNT("IEP"),
    ISRAELINEWSHEKEL("ILS"), ITALIANLIRA("ITL"), JAMAICANDOLLAR("JMD"), JAPANESEYEN("JPY"), JERSEYPOUND("JEP"), JORDANIANDINAR("JOD"),
    KAZAKHSTANITENGE("KZT"), KENYANSHILLING("KES"), KIRIBATIDOLLAR("KID"), KUWAITIDINAR("KWD"), KYRGYZSTANISOM("KGS"), LAOKIP("LAK"),
    LEBANESEPOUND("LBP"), LESOTHOLOTI("LSL"), LIBERIANDOLLAR("LRD"), LIBYANDINAR("LYD"), LITECOIN("LTC"), LITHUANIANLITAS("LTL"),
    LUXEMBOURGFRANC("LUF"), MACANESEPATACA("MOP"), MACEDONIANDENAR("MKD"), MALAGASYARIARY("MGA"), MALAGASYFRANC("MGF"),
    MALAWIANKWACHA("MWK"), MALAYSIANRINGGIT("MYR"), MALDIVIANRUFIYAA("MVR"), MALTESELIRA("MTL"), MANXPOUND("IMP"),
    MAURITANIANOLDOUGUIYA("MRO"), MAURITANIANOUGUIYA("MRU"), MAURITIANRUPEE("MUR"), MEXICANPESO("MXN"), MOLDOVANLEU("MDL"),
    MONGOLIANTUGRIK("MNT"), MOROCCANDIRHAM("MAD"), MOZAMBIQUEMETICAL("MZM"), MOZAMBIQUENEWMETICAL("MZN"), MYANMARKYAT("MMK"),
    NAMIBIANDOLLAR("NAD"), NEPALESERUPEE("NPR"), NETHERLANDSANTILLEANGUILDER("ANG"), NEWTAIWANDOLLAR("TWD"), NEWZEALANDDOLLAR("NZD"),
    NICARAGUANCORDOBAORO("NIO"), NIGERIANNAIRA("NGN"), NIUEDOLLAR("NONE"), NORTHKOREANWON("KPW"), NORWEGIANKRONER("NOK"),
    OMANIRIAL("OMR"), PAKISTANIRUPEE("PKR"), PALLADIUM("XPD"), PANAMANIANBALBOA("PAB"), PAPUANEWGUINEANKINA("PGK"), PARAGUAYANGUARANI("PYG"),
    PERUVIANNUEVOSOL("PEN"), PHILIPPINEPESO("PHP"), PITCAIRNISLANDSDOLLAR("PND"), POLISHOLDZLOTY("PLZ"), POLISHZLOTY("PLN"),
    PORTUGUESEESCUDO("PTE"), QATARIRIYAL("QAR"), ROMANIANLEU("ROL"), ROMANIANNEWLEU("RON"), RTGSDOLLAR("ZWB"), RUSSIANRUBLE("RUB"),
    RWANDANFRANC("RWF"), SAHRAWIPESETA("NONE"), SAINTHELENAPOUND("SHP"), SAMOANTALA("WST"), SAOTOMEANDPRINCIPEDOBRA("STN"),
    SAOTOMEANDPRINCIPEOLDDOBRA("STD"), SAUDIRIYAL("SAR"), SERBIANDINAR("RSD"), SERBIANOLDDINAR("CSD"), SEYCHELLESRUPEE("SCR"),
    SIERRALEONEANLEONE("SLL"), SINGAPOREDOLLAR("SGD"), SLOVAKKORUNA("SKK"), SLOVENIANTOLAR("SIT"), SOLOMONISLANDSDOLLAR("SBD"),
    SOMALISHILLING("SOS"), SOUTHAFRICANRAND("ZAR"), SOUTHKOREANWON("KRW"), SOUTHSUDANESEPOUND("SSP"), SPANISHPESETA("ESP"), SRILANKANRUPEE("LKR"),
    SUDANESEDINAR("SDD"), SUDANESEOLDPOUND("SDP"), SUDANESEPOUND("SDG"), SURINAMEGUILDER("SRG"), SURINAMESEDOLLAR("SRD"), SWAZILANDLILANGENI("SZL"),
    SWEDISHKRONA("SEK"), SWISSFRANC("CHF"), SYRIANPOUND("SYP"), TAIWANDOLLAR("TWD"), TAJIKISTANISOMONI("TJS"), TANZANIANSHILLING("TZS"), THAIBAHT("THB"),
    TONGANPAANGA("TOP"), TRANSNISTRIANRUBLE("PRB"), TRINIDADANDTOBAGODOLLAR("TTD"), TUNISIANDINAR("TND"), TURKISHLIRA("TRY"), TURKISHOLDLIRA("TRL"),
    TURKMENISTANMANAT("TMM"), TURKMENISTANNEWMANAT("TMT"), TUVALUANDOLLAR("TVD"), UGANDANSHILLING("UGX"), UGANDAOLDSHILLING("UGS"),
    UKRAINIANHRYVNIA("UAH"), UNITEDARABEMIRATESDIRHAM("AED"), UNITEDSTATESDOLLAR("USD"), URUGUAYANOLDPESO("UYP"), URUGUAYANPESO("UYU"),
    UZBEKISTANSOM("UZS"), VANUATUVATU("VUV"), VENEZUELANBOLIVAR("VEB"), VENEZUELANBOLIVARFUERTE("VEF"), VENEZUELANBOLIVARSOBERANO("VES"),
    VIETNAMESEDONG("VND"), WESTAFRICANCFAFRANC("XOF"), YEMENIRIAL("YER"), YUGOSLAVDINAR("YUN"), ZAMBIANKWACHA("ZMW"), ZIMBABWEDOLLAR("ZWL"), NOTHINGFOUND("Nothing Found");

    private static final Logger logger = LogManager.getLogger(Currencies.class);


    private String currencyName;

    Currencies(String currencyName) {
        this.setName(currencyName);
    }

    public String getName() {
        return currencyName;
    }

    public void setName(String name) {
        this.currencyName = name;
    }

    public static Currencies valueOfName(final String currencyName) {
        final String enumName = currencyName.toUpperCase().replaceAll(" ", "_");
        try {
            return valueOf(enumName);
        } catch (final IllegalArgumentException e) {
            return Currencies.NOTHINGFOUND;
        }
    }

    @Override
    public String toString() {
        return "Currencies{" +
                "Currency Abbreviation='" + currencyName + '\'' +
                '}';
    }
}
